site_name: Fiware-Orion
site_url: https://fiware-orion.readthedocs.org
repo_url: https://github.com/telefonicaid/fiware-orion.git
site_description: Orion Context Broker Documentation
docs_dir: doc/manuals
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
  - Home: index.md
  - 'Getting Started': 'quick_start_guide.md'
  - 'User & Programmers Manual':
      - 'Introduction': 'user/index.md'
      - 'API Walkthrough': 'user/walkthrough_apiv1.md'
      - 'Adding entities and attributes': 'user/append_and_delete.md'
      - 'Attribute Metadata': 'user/metadata.md'
      - 'Empty Types': 'user/empty_types.md'
      - 'Structured values for attributes': 'user/structured_attribute_valued.md'
      - 'Filtering': 'user/filtering.md'
      - 'Pagination': 'user/pagination.md'
      - 'Geolocation': 'user/geolocation.md'
      - 'Context Providers': 'user/context_providers.md'
      - 'Updating Registrations and Subscriptions': 'user/updating_regs_and_subs.md'
      - 'Multi tenancy': 'user/multitenancy.md'
      - 'Entity service paths': 'user/service_path.md'
      - 'Context Broker federation': 'user/federation.md'
      - 'Duration (for registrations and subscriptions)': 'user/duration.md'
      - 'Mixing standard and convenience operations': 'user/std_conv_mix.md'
      - 'HTTP and NGSI response codes': 'user/http_and_ngsi_sc.md'
      - 'Security considerations': 'user/security.md'
      - 'Known limitations': 'user/known_limitations.md'
      - 'Forbidden characters': 'user/forbidden_characters.md'
      - 'Docker': 'user/docker.md'
      - 'Considerations on NGSIv1 and NGSIv2 coexistence': 'user/v1_v2_coexistence.md'
  - 'Installation & Administration Manual':
      - 'Introduction': 'admin/index.md'
      - 'Installing Orion': 'admin/install.md'
      - 'Building from Sources': 'admin/build_source.md'
      - 'Running Orion as system service': 'admin/running.md'
      - 'Running Orion from command line': 'admin/cli.md'
      - 'Database administration': 'admin/database_admin.md'
      - 'Data model': 'admin/database_model.md'
      - 'Logs': 'admin/logs.md'
      - 'Watchdog': 'admin/watchdog.md'
      - 'Rush relayer': 'admin/rush.md'
      - 'Management REST interface': 'admin/management_api.md'
      - 'Statistics': 'admin/statistics.md'
      - 'Performance tuning': 'admin/perf_tuning.md'
      - 'Upgrading from previous to 0.14.1': 'admin/upgrading_crossing_0-14-1.md'
      - 'Upgrading from previous to 0.19.0': 'admin/upgrading_crossing_0-19-0.md'
      - 'Upgrading from previous to 0.21.0': 'admin/upgrading_crossing_0-21-0.md'
      - 'Sanity check procedures': 'admin/sanity_check.md'
      - 'Diagnosis procedures': 'admin/diagnosis.md'
