blank_issues_enabled: true
contact_links:
  - name: Orion documentation
    url: https://fiware-orion.readthedocs.io/en/master/
    about: check the documentation before asking help or reporting a bug.
  - name: Community Support
    url: https://stackoverflow.com/questions/ask?tags=fiware-orion+fiware
    about: |
      Volunteers from the Open Source FIWARE community monitor the ğšğš’ğš ğšŠğš›ğš tag
      and related tags over on Stack Overflow. For ğ—±ğ—²ğ˜ƒğ—²ğ—¹ğ—¼ğ—½ğ—ºğ—²ğ—»ğ˜ ğ—¾ğ˜‚ğ—²ğ˜€ğ˜ğ—¶ğ—¼ğ—»ğ˜€ ğ—¼ğ—»ğ—¹ğ˜† you can ask questions
      over on Stack Overflow provided you follow their rules and guidance on posting and respond to any feedback given.
      
      Stack Overflow is a crowd-sourced question and answer website for professional and enthusiast programmers. It is not affliated with this
      software and ğ—±ğ—¼ğ—²ğ˜€ ğ—»ğ—¼ğ˜ ğ—®ğ—»ğ˜€ğ˜„ğ—²ğ—¿ ğ—°ğ˜‚ğ˜€ğ˜ğ—¼ğ—ºğ—²ğ—¿ ğ˜€ğ—²ğ—¿ğ˜ƒğ—¶ğ—°ğ—² ğ—¿ğ—²ğ—¹ğ—®ğ˜ğ—²ğ—± ğ—¾ğ˜‚ğ—²ğ˜€ğ˜ğ—¶ğ—¼ğ—»ğ˜€.
      
      Do not raise a Stack Overflow question for bug reports or feature requests, stick with opening an issue directly within this repository.
