# Note that mongo container is started before Orion, as Orion needs it
# as dependency and reserve the order has been found problematic in some
# low resource hosts
mongo:
  image: mongo:3.4
  command: --nojournal

orion:
  image: fiware/orion-ld
  links:
    - mongo
  ports:
    - "1026:1026"
  command: -dbhost mongo

