# Note that mongo container is started before Orion, as Orion needs it
# as dependency and reserve the order has been found problematic in some
# low resource hosts
mongo:
  image: mongo:2.6
  command: --smallfiles --nojournal

orion:
  image: fiware/orion
  links:
    - mongo
  ports:
    - "1026:1026"
  command: -dbhost mongo

