name: Publish rpm from master

on:
  schedule:
    # every night at one
    - cron: '0 1 * * *'
  push:
    branches:
      - master

env:
  CI_IMAGE: fiware/orion-ci:rpm8

jobs:
  build-rpm-release:

    runs-on: ubuntu-18.04
    if: github.event_name == 'push'

    steps:

      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build & Push
        id: rpm_build
        run: |
          ./.github/build-and-push-rpm.sh ${{ secrets.NEXUS_PASSWORD }} release

  build-rpm-nightly:

    runs-on: ubuntu-18.04
    if: github.event_name == 'schedule'

    steps:

      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build & Push
        id: rpm_build
        run: |
          ./.github/build-and-push-rpm.sh ${{ secrets.NEXUS_PASSWORD }} nightly